<a href="https://colab.research.google.com/github/tabismohd2006/Numpy/blob/main/Yet_another_copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy

In [ ]:
pip install numpy

import numpy

In [ ]:
import numpy as np

Creatinng  numpy Arrays

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


two dimensionaal array

In [ ]:
import numpy as np
arr = np.array([
     [1,2,3],
     [4,5,6]
 ])
print(arr)

[[1 2 3]
 [4 5 6]]


three dimensionaal array

In [ ]:
import numpy as np
arr = np.array([
     [[1,2,],[3,4]],
     [[5,6], [7,8]]
 ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Attribute

In [ ]:
import numpy as np
arr = np.array([
     [1,2,3],
     [4,5,6]
 ])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
size: 6
Data Type: int64


special Arrays

In [ ]:
import numpy as np
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ones Array np.ones

In [ ]:
import numpy as np
arr = np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.empty

In [ ]:
import numpy as np
arr = np.empty((2,3))
print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


np.full

In [ ]:
import numpy as np
arr = np.full((3,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


np.eye()-identity matrix

In [ ]:
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


np.arrange

In [ ]:
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


np.linspace

In [ ]:
import numpy as np
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


np.random,rand()

In [ ]:
import numpy as np
arr = np.random.rand(3,3)
print(arr)

[[0.38756458 0.82193299 0.62735422]
 [0.54626838 0.83733912 0.44682483]
 [0.85800085 0.51808508 0.26315723]]


np.random.randint()

In [ ]:
import numpy as np
arr = np.random.randint(1,100,(3,4))
print(arr)

[[ 6 23 55 44]
 [22 71  5 59]
 [44 75 97 95]]


np.diag

In [ ]:
import numpy as np
arr = np.diag([5,10,15])
print(arr)

[[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]


Reshaping arrays

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print("original Array:")
print(arr)
new_arr = arr.reshape(2,3)
print("/nReshaped array:")
print(new_arr)

original Array:
[10 20 30 40 50 60]
/nReshaped array:
[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(3,2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,2,2)
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
